remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
title: MAULI PATEL
description: Welcome to my Data Science portfolio! I'm Mauli Patel, an aspiring data scientist passionate about solving real-world problems using data. This portfolio showcases my hands-on projects in data analysis, machine learning, data visualization, and Python programming. Each project highlights my skills in extracting insights, building models, and telling stories with data. Feel free to explore my work, read through my case studies, and connect with me on LinkedIn!
